// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAVhfTXp0xHnjH-NjHH6uGNObgdfVthA0',
    appId: '1:312253214276:web:bbdf21560ab01bdd09d611',
    messagingSenderId: '312253214276',
    projectId: 'booking-transition',
    authDomain: 'booking-transition.firebaseapp.com',
    databaseURL: 'https://booking-transition-default-rtdb.firebaseio.com',
    storageBucket: 'booking-transition.appspot.com',
    measurementId: 'G-ZFSTZK4J9V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBF2haJsByirDF-bHH5IvrU4QO-xFO-tOQ',
    appId: '1:312253214276:android:38674cf0c03af49409d611',
    messagingSenderId: '312253214276',
    projectId: 'booking-transition',
    databaseURL: 'https://booking-transition-default-rtdb.firebaseio.com',
    storageBucket: 'booking-transition.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCreRadQbUFDhz8HxzAVaLxF4oM62i6AcI',
    appId: '1:312253214276:ios:c0193fea6de8d24409d611',
    messagingSenderId: '312253214276',
    projectId: 'booking-transition',
    databaseURL: 'https://booking-transition-default-rtdb.firebaseio.com',
    storageBucket: 'booking-transition.appspot.com',
    iosClientId: '312253214276-k06be4ns7que2psa5nade0dhijt0pa1l.apps.googleusercontent.com',
    iosBundleId: 'com.example.bookingTransitionFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCreRadQbUFDhz8HxzAVaLxF4oM62i6AcI',
    appId: '1:312253214276:ios:c12f6dcbaf02528009d611',
    messagingSenderId: '312253214276',
    projectId: 'booking-transition',
    databaseURL: 'https://booking-transition-default-rtdb.firebaseio.com',
    storageBucket: 'booking-transition.appspot.com',
    iosClientId: '312253214276-piq5qsh9n63f9k47pasfv5at4d3grqhc.apps.googleusercontent.com',
    iosBundleId: 'com.example.bookingTransitionFlutter.RunnerTests',
  );
}
